name: Test Compress-Archive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-compress:
    runs-on: windows-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Create Test Files
      - name: Create Test Files
        run: |
          mkdir test-folder
          echo "This is a test file." > test-folder/test-file.txt

      #3 Compress Test Files
      - name: Compress Test Files
        run: |
          powershell Compress-Archive -Path test-folder\* -DestinationPath test-archive

      #4 Upload Test Archive
      - name: Upload Test Archive
        uses: actions/upload-artifact@v4
        with:
          name: test-archive
          path: test-folder
